# -*- coding: utf-8 -*-
"""Inital classification model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gkJQmPY95HI5bdgcflVD0pN1xWtbdXQ3
"""

# Traffic Sign Recognition using SVM (Single Code)

import os, cv2, random
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report


# Load dataset automatically (uses previous kagglehub path)
images = []
labels = []

for root, dirs, files in os.walk(path):

    folder = os.path.basename(root)

    if not folder.isdigit():
        continue

    for f in files:
        if f.endswith((".png",".jpg",".ppm")):

            img_path = os.path.join(root,f)

            img = cv2.imread(img_path)
            img = cv2.resize(img,(32,32))
            img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

            images.append(img.flatten())
            labels.append(int(folder))


X = np.array(images)
y = np.array(labels)

print("Dataset:", X.shape)
print("Classes:", len(np.unique(y)))


# Normalize
scaler = StandardScaler()
X = scaler.fit_transform(X)


# Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)


# SVM Model
model = SVC(
    kernel="rbf",
    C=10,
    gamma="scale"
)

# Train
model.fit(X_train,y_train)


# Predict
pred = model.predict(X_test)


# Accuracy
print("SVM Accuracy:", accuracy_score(y_test,pred)*100,"%")

print(classification_report(y_test,pred))


# Show one prediction
i = random.randint(0,len(X_test)-1)

plt.imshow(
    X_test[i].reshape(32,32),
    cmap="gray"
)

plt.axis("off")
plt.show()

print("Predicted:", pred[i])
print("Actual:", y_test[i])